# Vectors, matrices and multidimensional arrays

[NumPy manual (latest version, ReadTheDocs)](https://numpy.readthedocs.io/en/latest/index.html)

In [1]:
import numpy as np

### NumPy arrays
* **NOT THE SAME AS PYTHON LISTS**. All array elements have same data type; arrays are fixed size. (Need to edit the array? create a new one.)

Attributes:
- _shape_: tuple; contains # of elements for each axis of the array
- _size_: total # of elements
- _ndim_: number of dimensions (axes)
- _nbytes_: number of bytes used for storage
- _dtype_: datatype

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])
type(data)

numpy.ndarray

In [3]:
data.ndim, data.shape, data.size, data.dtype, data.nbytes

(2, (3, 2), 6, dtype('int64'), 48)

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

### Data types:
* int (integer: 8, 16, 32, 64)
* uint (unsigned integer: 8, 16, 32, 64)
* bool (boolean)
* float (floating-point: 16, 32, 64, 128)
* complex (comple floating-point: 64, 128, 256)

In [5]:
np.array([1, 2, 3], dtype=np.int)

array([1, 2, 3])

In [6]:
np.array([1, 2, 3], dtype=np.float)

array([1., 2., 3.])

In [7]:
np.array([1, 2, 3], dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
data = np.array([1, 2, 3], dtype=np.float)
data.dtype, data

(dtype('float64'), array([1., 2., 3.]))

In [9]:
data = np.array([1, 2, 3], dtype=np.int)
data.dtype, data

(dtype('int64'), array([1, 2, 3]))

In [10]:
data = np.array([1, 2, 3], dtype=np.float)
data.dtype, data

(dtype('float64'), array([1., 2., 3.]))

Once created, dtype cannot be changed. 
Create a copy with "typecasted" new values:

In [11]:
data.astype(np.int)

array([1, 2, 3])

Data types can get "promoted" to support operations:

In [12]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)
(d1+d2).dtype

dtype('complex128')

Some cases may require creation of arrays set to appropriate data types. The default is 'float'.



In [13]:
np.sqrt(np.array([-1, 0, 1]))

/home/bjpcjp/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan,  0.,  1.])

In [14]:
np.sqrt(np.array([-1, 0, 1], dtype=complex))

array([0.+1.j, 0.+0.j, 1.+0.j])

### Real and imaginary parts
* All numpy arrays (not just complex vals) have real & imaginary attributes.

In [15]:
data = np.array([1, 2, 3], dtype=complex)

In [16]:
print(data,"\n",data.real,"\n",data.imag)

[1.+0.j 2.+0.j 3.+0.j] 
 [1. 2. 3.] 
 [0. 0. 0.]


### Array data in memory
* Stored as contiguous data in memory. In the case of 2D arrays,
* Two options:
    - __Row-major__ (row-wise storage; C std.)
    - __Column-major__ (column-wise storage; Fortran std.)
* Numpy default is __row-major__.
* To specifiy, use keyword argument *order='C'* or *order='F'*

### Creating Arrays
![array-gen-funcs](pics/array-gen-funcs.png)
![array-gen-funcs2](pics/array-gen-funcs2.png)

### Arrays created from lists and other array-like objects

In [17]:
data = np.array([1, 2, 3, 4])

In [18]:
data.ndim, data.shape

(1, (4,))

In [19]:
data = np.array([[1, 2], [3, 4]])

In [20]:
data.ndim, data.shape

(2, (2, 2))

### Arrays filled with constant values

In [21]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
data = np.ones(4)
data

array([1., 1., 1., 1.])

In [24]:
x1 = 5.4 * data; x1

array([5.4, 5.4, 5.4, 5.4])

numpy __full()__: create array filled with ones, then muliply array with desired fill value.

In [26]:
x2 = np.full(10, 5.4)
x2

array([5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4])

numpy __empty()__: unitialized data

In [29]:
x1 = np.empty(5); x1

array([6.94147542e-310, 6.94147542e-310, 1.58101007e-322, 0.00000000e+000,
       2.37151510e-322])

In [30]:
x1.fill(3.0); x1

array([3., 3., 3., 3., 3.])

### Arrays filled with sequences

In [31]:
# np.arange (3rd arg = increment)
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [32]:
# np.linspace (3rd arg = #total points)
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
# np.logspace
np.logspace(0, 2, 4)  # 4 data points between 10**0=1 to 10**2=100

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

### Mesh-grid arrays
* Given two 1D coordinate arrays, generate 2D coordinate array.
* Often used when plotting function over two variables (ex: contour plots).

In [34]:
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])


In [35]:
X, Y = np.meshgrid(x, y)

In [36]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [37]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [38]:
(X + Y) ** 2

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [40]:
np.mgrid?

Type:        MGridClass
String form: <numpy.lib.index_tricks.MGridClass object at 0x7fc7f813bfd0>
File:        ~/anaconda3/lib/python3.6/site-packages/numpy/lib/index_tricks.py
Docstring:  
`nd_grid` instance which returns a dense multi-dimensional "meshgrid".

An instance of `numpy.lib.index_tricks.nd_grid` which returns an dense
(or fleshed out) mesh-grid when indexed, so that each returned argument
has the same shape.  The dimensions and number of the output arrays are
equal to the number of indexing dimensions.  If the step length is not a
complex number, then the stop is not inclusive.

However, if the step length is a **complex number** (e.g. 5j), then
the integer part of its magnitude is interpreted as specifying the
number of points to create between the start and stop values, where
the stop value **is inclusive**.

Returns
----------
mesh-grid `ndarrays` all of the same dimensions

See Also
--------
numpy.lib.index_tricks.nd_grid : class of `ogrid` and `mgrid` objects
ogrid : 

In [41]:
np.ogrid?

Type:        OGridClass
String form: <numpy.lib.index_tricks.OGridClass object at 0x7fc7f80fee48>
File:        ~/anaconda3/lib/python3.6/site-packages/numpy/lib/index_tricks.py
Docstring:  
`nd_grid` instance which returns an open multi-dimensional "meshgrid".

An instance of `numpy.lib.index_tricks.nd_grid` which returns an open
(i.e. not fleshed out) mesh-grid when indexed, so that only one dimension
of each returned array is greater than 1.  The dimension and number of the
output arrays are equal to the number of indexing dimensions.  If the step
length is not a complex number, then the stop is not inclusive.

However, if the step length is a **complex number** (e.g. 5j), then
the integer part of its magnitude is interpreted as specifying the
number of points to create between the start and stop values, where
the stop value **is inclusive**.

Returns
----------
mesh-grid `ndarrays` with only one dimension :math:`\neq 1`

See Also
--------
np.lib.index_tricks.nd_grid : class of `ogri

### Uninitialized arrays
* Use __np.empty__ instead of np.zeros if wanting to avoid initialization step. (Saves time when building large arrays.)

In [42]:
np.empty(3, dtype=np.float)

array([1., 2., 3.])

### Creating arrays with properties of other arrays

Typical use case: a function that takes arrays of unspecified type & size as arguments & requires working arrays of the same type & size.

* __np.ones_like__
* __np.zeros_like__
* __np.full_like__
* __np.empty_like__

In [43]:
def f(x):
    y = np.ones_like(x)
    return y

a = [1,2,3,4]
f(a)

array([1, 1, 1, 1])

### Creating matrix arrays

* __np.identity()__: creates square matrix with ones on diagonal, zero elsewhere.

In [44]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

* __np.eye()__: ones on diagonal, optionally offset

In [45]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [46]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

* __diag()__: arbitrary 1D array on the diagonal of a matrix

In [47]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

## Index and slicing

### One-dimensional arrays
![array-slice-funcs](pics/array-slice-funcs.png)

In [48]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
a[0]  # the first element

0

In [50]:
a[-1] # the last element

10

In [51]:
a[4]  # the fifth element, at index 4

4

In [52]:
a[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a[1:-1:2]

array([1, 3, 5, 7, 9])

In [54]:
a[:5] # first five elements

array([0, 1, 2, 3, 4])

In [55]:
a[-5:] # last five elements

array([ 6,  7,  8,  9, 10])

In [56]:
a[::-2] # every 2nd value in reverse order

array([10,  8,  6,  4,  2,  0])

## Multidimensional arrays

In [157]:
f = lambda m, n: n + 10 * m

In [158]:
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [159]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41, 51])

In [160]:
A[1, :]  # the second row

array([10, 11, 12, 13, 14, 15])

In [161]:
A[:3, :3]  # upper left diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [162]:
A[3:, :3]  # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [163]:
A[::2, ::2]  # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [164]:
A[1::2, 1::3]  # every (2nd,3rd) element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

### Views
* Subarray extractions using slice ops are view of same underlying data. (Refer to same data, but using different "strides".)

In [165]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [166]:
B[:, :] = 0
A

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [167]:
C = B[1:3, 1:3].copy()
C

array([[0, 0],
       [0, 0]])

In [168]:
C[:, :] = 1
C

array([[1, 1],
       [1, 1]])

In [169]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Fancy indexing and Boolean-valued indexing
* Arrays can be indexed using another array, a list, or sequence of integers.

In [170]:
A = np.linspace(0, 1, 11)
A

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [171]:
A[np.array([0, 2, 4])]

array([ 0. ,  0.2,  0.4])

In [172]:
A[[0, 2, 4]]

array([ 0. ,  0.2,  0.4])

In [173]:
# boolean-based indexing - great for filtering!
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [174]:
A[A > 0.5]

array([ 0.6,  0.7,  0.8,  0.9,  1. ])

* arrays from fancy & boolean indexing are new, independent arrays - not just views of existing arrays.

In [175]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
indices = [2, 4, 6]
B = A[indices]
B

array([2, 4, 6])

In [177]:
B[0] = -1  # this does not affect A
B

array([-1,  4,  6])

In [178]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
A[indices] = -1
A

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [180]:
A = np.arange(10)

In [181]:
B = A[A > 5]

In [182]:
B[0] = -1  # this does not affect A

In [183]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [184]:
A[A > 5] = -1

In [185]:
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

### Reshaping and resizing ops
![reshape](pics/reshape-ops.png)
* Does not modify underlying data, only changes *stride* attribute

In [186]:
data = np.array([[1, 2], [3, 4]])

In [187]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [188]:
data.reshape(4)

array([1, 2, 3, 4])

In [189]:
data

array([[1, 2],
       [3, 4]])

In [190]:
data.flatten()

array([1, 2, 3, 4])

In [191]:
data.flatten().shape

(4,)

In [192]:
data.ravel()

array([1, 2, 3, 4])

In [193]:
data = np.arange(0, 5)
data

array([0, 1, 2, 3, 4])

In [194]:
data[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [195]:
data[np.newaxis, :]

array([[0, 1, 2, 3, 4]])

In [196]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [197]:
# stack vertically along axis 0
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [198]:
# stack horizontally along axis 0
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [199]:
data = data[:, np.newaxis]
data

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [200]:
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

### Vectorized expressions
* Designed to avoid need for "*for*" loops.

### Arithmetic operations
![arithmetic-ops](pics/arithmetic-ops.png)

In [201]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
x+y

array([[ 6,  8],
       [10, 12]])

In [202]:
x + y

array([[ 6,  8],
       [10, 12]])

In [203]:
y - x

array([[4, 4],
       [4, 4]])

In [204]:
x * y

array([[ 5, 12],
       [21, 32]])

In [205]:
y / x

array([[ 5.        ,  3.        ],
       [ 2.33333333,  2.        ]])

In [206]:
x * 2

array([[2, 4],
       [6, 8]])

In [207]:
2 ** x

array([[ 2,  4],
       [ 8, 16]])

In [208]:
y / 2

array([[ 2.5,  3. ],
       [ 3.5,  4. ]])

In [209]:
(y / 2).dtype

dtype('float64')

In [210]:
x = np.array([1, 2, 3, 4]).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [211]:
z = np.array([1, 2, 3, 4])
z

array([1, 2, 3, 4])

In [212]:
# incompatible size/shape
x / z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [ ]:
z = np.array([[2, 4]])

In [ ]:
z.shape

In [ ]:
x / z

In [ ]:
zz = np.concatenate([z, z], axis=0)
zz

In [ ]:
x / zz

In [ ]:
z = np.array([[2], [4]])
z.shape

In [ ]:
x / z

In [ ]:
zz = np.concatenate([z, z], axis=1)
zz

In [ ]:
x / zz

In [ ]:
x = np.array([[1, 3], [2, 4]])
x = x + y
x

In [ ]:
x = np.array([[1, 3], [2, 4]])
x += y
x

### Elementwise functions
![element-wise-math](pics/element-wise-math-functs.png)

In [ ]:
x = np.linspace(-1, 1, 11)
x

In [ ]:
y = np.sin(np.pi * x)
y

In [ ]:
# round FP numbers to 4 decimals
np.round(y, decimals=4)

In [ ]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

In [ ]:
np.sin(x) ** 2 + np.cos(x) ** 2

![element-wise-math](pics/element-wise-math.png)

* Sometimes need to define new functions that use NumPy arrays element-by-element.

In [ ]:
def heaviside(x):
    return 1 if x > 0 else 0

heaviside(-1), heaviside(1.5)

In [ ]:
# won't work
heaviside(np.linspace(-5, 5, 11))

In [ ]:
# use vectorize to improve a non-vectorized function
heaviside = np.vectorize(heaviside)

In [ ]:
# works, but relatively slow.
# better to use boolean-valued arrays (to be discussed later)
# use as quick-n-dirty check
heaviside(x)

### Aggregate functions
* accepts array inputs, returns scalar outputs
![aggregate-funcs](pics/aggregate-funcs.png)

In [ ]:
data = np.random.normal(size=(15,15))

In [ ]:
np.mean(data), data.mean()

In [ ]:
data = np.random.normal(size=(5, 10, 15))

In [ ]:
data.sum(axis=0).shape

In [ ]:
data.sum(axis=(0, 2)).shape

In [ ]:
data.sum()

In [ ]:
data = np.arange(1,10).reshape(3,3)
data

In [ ]:
data.sum()

In [ ]:
data.sum(axis=0)

In [ ]:
data.sum(axis=1)

### Boolean arrays and vectorized conditional expressions
* Enables you to avoid using if statements

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
a<b

In [ ]:
np.all(a<b), np.any(a<b)

In [ ]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elemment in b")
else:
    print("All elements in b are smaller than their corresponding element in a")

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
x>0

In [ ]:
1 * (x>0)

In [ ]:
x * (x>0)

In [ ]:
# conditional computing -- defining piecewise functions

x = np.linspace(-5, 5, 11)

def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

In [ ]:
pulse(x, position=-2, height=1, width=5)

In [ ]:
pulse(x, position=1, height=1, width=5)

### Conditional / Logical Functions
![conditionals-logicals](pics/conditional-logical-funcs.png)

In [ ]:
def pulse(x, position, height, width):
    return height * np.logical_and(x >= position, x <= (position + width))

In [ ]:
x = np.linspace(-4, 4, 9)
x

In [ ]:
np.where(x < 0, x**2, x**3)

In [ ]:
np.select([x < -1, x < 2, x >= 2],
          [x**2  , x**3 , x**4])

In [ ]:
np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2], 
          [x**2,    x**3,    x**4])

In [ ]:
x[abs(x) > 2]

In [ ]:
np.nonzero(abs(x) > 2)

In [ ]:
x[np.nonzero(abs(x) > 2)]

### Set operations
* Manages unordered collections of unique objects.
![set-funcs](pics/set-funcs.png)

In [ ]:
a = np.unique([1,2,3,3])
b = np.unique([2,3,4,4,5,6,5])

In [ ]:
np.in1d(a, b)

In [ ]:
# testing for single element presence
1 in a

In [ ]:
1 in b

In [ ]:
np.all(np.in1d(a, b))

In [ ]:
np.union1d(a, b)

In [ ]:
np.intersect1d(a, b)

In [ ]:
np.setdiff1d(a, b)

In [ ]:
np.setdiff1d(b, a)

### Operations on arrays
![array-funcs](pics/array-funcs.png)

In [ ]:
data = np.arange(9).reshape(3, 3)
data

In [ ]:
np.transpose(data)

In [ ]:
data = np.random.randn(1, 2, 3, 4)
data

In [ ]:
data.shape

In [ ]:
data.T.shape

### Matrix and vector operations
* NumPy uses . ("dot") to denote matrix multiplication.
![matrix-funcs](pics/matrix-funcs.png)

In [ ]:
A = np.arange(1, 7).reshape(2, 3)
A

In [ ]:
B = np.arange(1, 7).reshape(3, 2)
B

In [ ]:
np.dot(A, B)

In [ ]:
np.dot(B, A)

In [ ]:
A = np.arange(9).reshape(3, 3)
A

In [ ]:
x = np.arange(3)
x

In [ ]:
# dot operation can also be used for matrix-vector multiplication
np.dot(A, x), A.dot(x)

In [ ]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
A,B

In [ ]:
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))
Ap

In [ ]:
Ap = B.dot(A.dot(np.linalg.inv(B)))

In [ ]:
A = np.matrix(A)

In [ ]:
B = np.matrix(B)

In [ ]:
Ap = B * A * B.I

In [ ]:
A = np.asmatrix(A)

In [ ]:
B = np.asmatrix(B)

In [ ]:
Ap = B * A * B.I

In [ ]:
Ap = np.asarray(Ap)

In [ ]:
np.inner(x, x)

In [ ]:
np.dot(x, x)

In [ ]:
y = x[:, np.newaxis]

In [ ]:
y

In [ ]:
np.dot(y.T, y)

In [ ]:
x = np.array([1, 2, 3])

In [ ]:
np.outer(x, x) 

In [ ]:
np.kron(x, x) 

In [ ]:
np.kron(x[:, np.newaxis], x[np.newaxis, :])

In [ ]:
np.kron(np.ones((2,2)), np.identity(2))

In [ ]:
np.kron(np.identity(2), np.ones((2,2)))

In [ ]:
x = np.array([1, 2, 3, 4])

In [ ]:
y = np.array([5, 6, 7, 8])

In [ ]:
np.einsum("n,n", x, y)

In [ ]:
np.inner(x, y)

In [ ]:
A = np.arange(9).reshape(3, 3)

In [ ]:
B = A.T

In [ ]:
np.einsum("mk,kn", A, B)

In [ ]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

# Versions

In [107]:
%reload_ext version_information
%version_information numpy

ImportError: No module named 'version_information'